name: a2z

volumes:
  world:

services:
  server:
    image: docker.pool.net.eu.org/a2z/server
    build: dedicated-server/
    init: true
    cpus: 3
    tty: true
    stdin_open: true
    ports:
      - 30024:25565
      - 15352:15352/udp
